### ISSUE TITLE
please publish new version out to npm?

### ISSUE THREAD

**Issue by jamesmanning** [astro/node-oembed#10]
PR #5 is a required change now for node 6.x and later since util.pump went from deprecated to gone, but the last published version in the npm registry is from before that fix.  Could you please publish a new version out to npm?  I'll point to this repo in the mean time but I'm sure others are hitting this issue as well. 😄

**Comment by astro** [comment]
Thanks for the nudge. Published as `v0.1.1` on npm: https://www.npmjs.com/package/oembed

I see there are now a number of parallel developments: https://github.com/astro/node-oembed/network Please open PRs if you see anything that would fit.
