### ISSUE TITLE
JSON does not work with soundcloud

### ISSUE THREAD

**Issue by morganlegal** [astro/node-oembed#7]
With Souncloud the discover function return { 'text/xml+oembed': 'https://soundcloud.com/oembed?url=http%3A%2F%2Fsoundcloud.com%2Ffutureisnow%2Ff-ck-up-some-commas&format=xml',
'text/json+oembed': 'https://soundcloud.com/oembed?url=http%3A%2F%2Fsoundcloud.com%2Ffutureisnow%2Ff-ck-up-some-commas&format=json' }
Since the constant MIME_OEMBED_XML is 'text/xml+oembed', it is impossible to get JSON format on Soundcloud

**Comment by astro** [comment]
Apologies, but I'm not currently maintaining this library. Please send a Pull Request. Thank you.
